name: Bibliography Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  bibcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check .bib files for duplicates
        run: |
          shopt -s globstar
          if grep -i "duplicate" **/*.bib; then
            echo "⚠️ Mögliche doppelte Einträge gefunden"
          else
            echo "✅ Keine doppelten Einträge"
          fi
